{
 "title": "ENTSOG-Monitor",
 "description": "Dashboard visualizing the Data from the ENTSOG",
 "tags": [ "open-data" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "balancingzones",
    "query": "select bzLabel from entsog.balancingzones"
   },
   {
    "name": "operator",
    "query": "select distinct tooperatorkey from entsog.interconnections"
   },
   {
    "name": "pointkeys",
    "query": "select pointlabel from entsog.operatorpointdirections where operatorkey='$operator'"
   }
  ]
 },
 "panels": [
  {
   "title": "Stromverbrauch & Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(periodfrom,$__interval),\n  sum(value/$__interval_ms*1000*60*60) AS \"flow\"\nFROM entsog.physical_flow\nWHERE\n  $__timeFilter(periodfrom) AND\n  operatorkey LIKE 'DE%' AND\n  directionkey = 'entry'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-272.15) AS \"temp_air\"\nFROM weather.ecmwf_eu\nWHERE\n  $__timeFilter(\"time\") AND\n  nuts_id = 'DE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "ENTSO-G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Firm Technical Capacity ENTSOG (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(periodfrom,$__interval),\n  operatorlabel AS metric,\n  sum(index) AS \"index\"\nFROM entsog.firm_technical\nWHERE\n  $__timeFilter(periodfrom)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Flow for $pointkeys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(periodfrom,$__interval),\n  concat('phys_',directionkey) AS metric,\n  sum(value) AS \"Physical\"\nFROM entsog.physical_flow\nWHERE\n  $__timeFilter(periodfrom) AND\n  pointlabel = '$pointkeys'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(periodfrom,$__interval),\n  concat('alloc_',directionkey) AS metric,\n  avg(value) AS \"Allocation_$pointkeys\"\nFROM entsog.allocation\nWHERE\n  $__timeFilter(periodfrom) AND\n  pointlabel = '$pointkeys'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Physical Flow for $operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  periodfrom AS \"time\",\n  value AS \"Physical\"\nFROM entsog.physical_flow\nWHERE\n  $__timeFilter(periodfrom) AND\n  operatorkey = '$operator'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  periodfrom AS \"time\",\n  value AS \"Allocation\"\nFROM entsog.allocation\nWHERE\n  $__timeFilter(periodfrom) AND\n  operatorkey = '$operator'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSOG Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  pointtpmapx,\n  pointtpmapy\nFROM entsog.interconnections\nORDER BY 1"
    }
   ]
  }
 ]
}