{
 "title": "ENTSOE-Monitor",
 "description": "Monitor of the open available Data from the ENTSOG",
 "tags": [ "open-data" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "country", "query": "select name from entsoe.areas" }
  ]
 },
 "panels": [
  { "title": "Europa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actual Power Europe (sum over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum(actual_load/($__interval_ms/1000/3600)) AS \"actual_load\"\nFROM entsoe.query_load\nWHERE\n  $__timeFilter(index) AND\n  country IN ('DE','AT','FR','PL','IT','ES','PT','CH','BE','NL','GB','SE','NO')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum(forecasted_load/($__interval_ms/1000/3600)) AS \"forecasted_load\"\nFROM entsoe.query_load_forecast\nWHERE\n  $__timeFilter(index) AND\n  country IN ('DE','AT','FR','PL','IT','ES','PT','CH','BE','NL','GB','SE','NO')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum((biomass+\n  fossil_hard_coal+\n  geothermal+\n  nuclear+\n  \"fossil_brown_coal/lignite\"+\n  \"fossil_coal-derived_gas\"+\n  \"hydro_run-of-river_and_poundage\"+\n  waste+\n  solar+\n  wind_offshore+\n  wind_onshore+\n  other_renewable+\n  hydro_water_reservoir+\n  fossil_gas)\n  /($__interval_ms/1000/3600)) AS \"generation_sum\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum(actual_aggregated/10) AS \"forecasted_generation\",\n  sum(actual_consumption) AS \"forecasted_consumption\"\nFROM entsoe.query_generation_forecast\nWHERE\n  $__timeFilter(index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSOE-Power systems",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  lat,\n  lon,\n  capacity,\n  country,\n  energy_source\nFROM entsoe.powersystemdata\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSOE Day-Ahead-Prices (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  country AS metric,\n  avg(\"0\") AS \"\"\"0\"\"\"\nFROM entsoe.query_day_ahead_prices\nWHERE\n  $__timeFilter(index)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "ENTSO-E", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Load $country (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(actual_load) AS \"actual_load\"\nFROM entsoe.query_load\nWHERE\n  $__timeFilter(index) AND\n  country = '$country'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(forecasted_load) AS \"forecasted_load\"\nFROM entsoe.query_load_forecast\nWHERE\n  $__timeFilter(index) AND\n  country = '$country'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Erzeugungsleistung $country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  index AS \"time\",\n  biomass,\n  fossil_hard_coal,\n  geothermal,\n  nuclear,\n  \"fossil_brown_coal/lignite\",\n  \"fossil_coal-derived_gas\",\n  \"hydro_run-of-river_and_poundage\",\n  waste,\n  solar,\n  wind_offshore,\n  wind_onshore,\n  other_renewable\nFROM entsoe.query_installed_generation_capacity\nWHERE\n  $__timeFilter(index) AND\n  country = '$country'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stromerzeugung $country (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"index\",$__interval),\n  avg(biomass) as biomass,\n  avg(fossil_hard_coal) as fossil_hard_coal,\n  avg(geothermal) as geothermal,\n  avg(nuclear) as nuclear,\n  avg(\"fossil_brown_coal/lignite\") as \"fossil_brown_coal/lignite\",\n  avg(\"fossil_coal-derived_gas\") as \"fossil_coal-derived_gas\",\n  avg(\"hydro_run-of-river_and_poundage\") as \"hydro_run-of-river_and_poundage\",\n  avg(waste) as waste,\n  avg(solar) as solar,\n  avg(wind_offshore) as wind_offshore,\n  avg(wind_onshore) as wind_onshore,\n  avg(other_renewable) as other_renewable,\n  avg(hydro_water_reservoir) as hydro_water_reservoir,\n  avg(fossil_gas) as fossil_gas\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = '$country'\ngroup by 1\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "ENTSOE Day-Ahead-Prices (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  avg(\"0\") AS \"da_price\"\nFROM entsoe.query_day_ahead_prices\nWHERE\n  $__timeFilter(index) AND\n  country = '$country'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Compare RES forecast - with actual (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum(solar/($__interval_ms/1000/3600)) AS \"solar_fc\",\n  sum(wind_onshore/($__interval_ms/1000/3600)) AS \"wind_onshore_fc\",\n  sum(wind_offshore/($__interval_ms/1000/3600)) AS \"wind_offshore_fc\"\nFROM entsoe.query_wind_and_solar_forecast\nWHERE\n  $__timeFilter(index)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  sum(solar/($__interval_ms/1000/3600)) AS \"solar\",\n  sum(wind_onshore/($__interval_ms/1000/3600)) AS \"wind_onshore\",\n  sum(wind_offshore/($__interval_ms/1000/3600)) AS \"wind_offshore\"\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}