{
 "title": "GIE-Dashboard",
 "time": { "from": "now-13y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT name FROM gie.gie_agsi_country"
   },
   {
    "name": "agsi_company",
    "label": "Company (AGSI)",
    "query": "SELECT DISTINCT name FROM gie.gie_agsi_company WHERE parent = '${country}'"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gas Storage Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT distinct longitude, latitude, name, code, type FROM gie.gie_alsi_location"
    },
    {
     "rawSql": "SELECT distinct longitude, latitude, name, code, type FROM gie.gie_agsi_location"
    }
   ]
  },
  {
   "title": "sendout of ALSI LNG Terminals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(sendout) AS sendout,\n  code\nFROM gie.gie_alsi_country\nWHERE\n  $__timeFilter(gasdaystart)\nGROUP BY 1, code\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Gas in Storage AGSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "TWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(gasinstorage) AS gasinstorage,\n  code\nFROM gie.gie_agsi_country\nWHERE\n  $__timeFilter(gasdaystart)\nGROUP BY 1, code\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Annual Gas Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "TWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(consumption) AS AnnualConsumption,\n  name\nFROM gie.gie_agsi_country\nWHERE\n  $__timeFilter(gasdaystart)\nGROUP BY 1, name\nORDER BY 1"
    }
   ]
  },
  { "title": "ALSI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "daily total send-out capacity in ALSI LNG terminals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(dtrs) AS dtrs,\n  code\nFROM gie.gie_alsi_country\nWHERE\n  $__timeFilter(gasdaystart)\nGROUP BY 1, code\nORDER BY 1"
    }
   ]
  },
  {
   "title": "daily total send-out capacity in ALSI LNG terminals $country",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(dtrs) AS dtrs,\n  name\nFROM gie.gie_alsi_country\nWHERE\n  $__timeFilter(gasdaystart) AND name = '$country' \nGROUP BY 1, name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "daily total send-out capacity in ALSI LNG terminals $country",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(dtrs) AS dtrs,\n  name\nFROM gie.gie_alsi_country\nWHERE\n  $__timeFilter(gasdaystart) AND name = '$country' \nGROUP BY 1, name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "daily total send-out capacity in ALSI LNG terminals by location for $country",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(dtrs) AS dtrs,\n  gie_alsi_location.name\nFROM gie.gie_alsi_location\nJOIN (SELECT distinct parent, name from gie.gie_alsi_company where $__timeFilter(gasdaystart)) companies ON companies.name = gie.gie_alsi_location.parent\nWHERE\n  $__timeFilter(gasdaystart) AND companies.parent = '$country' \nGROUP BY 1, gie_alsi_location.name  \nORDER BY 1"
    }
   ]
  },
  { "title": "AGSI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Injection and Withdrawal of Gas Storages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "GWh/d" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(injection) AS injection,\n  avg(withdrawal) AS withdrawal,\n  code\nFROM gie.gie_agsi_country\nWHERE\n  $__timeFilter(gasdaystart)\nGROUP BY 1, code\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gas in Storage in $country",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "TWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(gasinstorage) AS gasInStorage,\n  name\nFROM gie.gie_agsi_country\nWHERE\n  $__timeFilter(gasdaystart) AND name = '$country' \nGROUP BY 1, name  \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gas in Storage by company in $country",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "TWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(gasinstorage) AS gasInStorage,\n  name\nFROM gie.gie_agsi_company \nWHERE\n  $__timeFilter(gasdaystart) AND parent = '$country' \nGROUP BY 1, name  \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gas in Storage by location for $agsi_company",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "TWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(gasdaystart,$__interval),\n  avg(gasinstorage) AS GasInStorage,\n  name\nFROM gie.gie_agsi_location\nWHERE\n  $__timeFilter(gasdaystart) AND parent = '$agsi_company' \nGROUP BY 1, name  \nORDER BY 1"
    }
   ]
  }
 ]
}