{
 "title": "JAO-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ENTSOE Day-Ahead-Prices and JAO (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  country AS metric,\n  avg(\"0\") AS \"Day-Ahead price\"\nFROM entsoe.query_day_ahead_prices\nWHERE\n  $__timeFilter(index)\n  and country = 'CH'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  corridor,\n  --avg(\"offeredCapacity\") AS \"offered_capacity\",\n  avg(\"auctionPrice\") AS \"JAO auction price\"\n  \n  \nFROM \"jao\".auctions\nWHERE\n  $__timeFilter(date)\n  and corridor like '%DE-CH%' \nGROUP BY 1, corridor\nORDER BY 1, corridor"
    }
   ]
  },
  {
   "title": "Resold quantity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total_query AS (\nSELECT * FROM jao.bids_daily \nUNION \nSELECT * FROM jao.bids_monthly\n)\nSELECT COUNT(*) FROM total_query WHERE \"resoldQuantity\" != 0;\n"
    }
   ]
  },
  {
   "title": "delivered days",
   "type": "piechart",
   "description": "for monthly bids",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"productMinutesDelivered\"/60/24 as \"days\",COUNT(\"productMinutesDelivered\") as \"value\"\nFROM jao.bids_monthly\nGROUP BY \"days\";"
    }
   ]
  }
 ]
}