{
 "title": "Open-NRW",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NUTS3",
    "query": "Select distinct nuts_id from nuts where level = 3 and country = 'DE' and SUBSTRING(nuts_id,1,3) = 'DEA' order by nuts_id"
   }
  ]
 },
 "panels": [
  { "title": "Solarkataster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Potential by NUTS3",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "Select \r\n  d.nuts_id, ST_AsGeoJSON(nuts.geometry) as geom, \r\n  sum(power) as power \r\nfrom solar d\r\nJoin nuts on d.nuts_id = nuts.nuts_id\r\nGroup by d.nuts_id, nuts.geometry"
    },
    {
     "rawSql": "Select \n  d.nuts_id, ST_AsGeoJSON(nuts.geometry) as geom, \n  sum(power) as power \nfrom solar d\nJoin nuts on d.nuts_id = nuts.nuts_id\nwhere d.nuts_id = '$NUTS3'\nGroup by d.nuts_id, nuts.geometry\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  nuts_id,\n  sum(power)/ 1000 AS \"Potential $NUTS3\" \nFROM solar\nwhere nuts_id = '$NUTS3'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  nuts_id,\n  count(power) AS \"possible Systems in $NUTS3\" \nFROM solar\nwhere nuts_id = '$NUTS3'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Azimuth Distribution",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  azimuth\nFROM solar\nWHERE nuts_id = '$NUTS3' and azimuth > 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tilt Distribution",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  tilt\nFROM solar\nWHERE nuts_id = '$NUTS3' and tilt > 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "System Power Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  power as \"system_power\"\nFROM solar\nwhere\n  nuts_id = '$NUTS3' and\n  power < 50\n\nORDER BY 1"
    }
   ]
  },
  { "title": "Wärmekataster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Heat Demand  by NUTS3",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "Select \r\n  d.nuts_id, ST_AsGeoJSON(nuts.geometry) as geom, \r\n  sum(demand) as demand \r\nfrom heat d\r\nJoin nuts on d.nuts_id = nuts.nuts_id\r\nGroup by d.nuts_id, nuts.geometry"
    },
    {
     "rawSql": "Select \n  d.nuts_id, ST_AsGeoJSON(nuts.geometry) as geom, \n  sum(demand) as demand \nfrom heat d\nJoin nuts on d.nuts_id = nuts.nuts_id\nwhere d.nuts_id = '$NUTS3'\nGroup by d.nuts_id, nuts.geometry\n\n\n"
    }
   ]
  },
  { "title": "European weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Average Irradiation Europe",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 12, "w": 6, "x": 7, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(ghi) AS \"ghi\",\n  ST_AsGeoJSON(geometry) AS \"geom\"\nFROM weather.ecmwf_eu eu JOIN nuts ON eu.nuts_id = nuts.nuts_id \nGROUP BY geom\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Europe Irradiation map",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  --$__timeGroupAlias(\"time\",$__interval),\n  --avg(temp_air-273.15) AS \"temp_air\",\n  avg(ghi/3600) AS \"ghi\",\n  --avg(\"wind_speed\") AS \"wind_speed\",\n  longitude,\n  latitude,\n  nuts_id\nFROM weather.ecmwf_eu\nWHERE\n  \"time\" = (SELECT MAX(\"time\") FROM  weather.ecmwf WHERE $__timeFilter(\"time\"))\n  \nGROUP BY longitude, latitude, nuts_id\n--, 1\n--ORDER BY 1"
    }
   ]
  }
 ]
}