{
 "title": "Weather Dashboard",
 "time": { "from": "now-14d", "to": "now-5d" },
 "templating": {
  "list": [
   {
    "name": "nuts_id",
    "query": "select distinct nuts_id from public.nuts"
   },
   { "name": "metric", "label": "Weather metrics", "query": "temp_air, wind_speed, ghi" }
  ]
 },
 "panels": [
  {
   "title": "Average Europe Heat map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  --$__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air\",\n  --avg(ghi/3600) AS \"ghi\",\n  --avg(\"wind_speed\") AS \"wind_speed\",\n  longitude,\n  latitude,\n  nuts_id\nFROM weather.ecmwf_eu\nWHERE\n  \"time\" = (SELECT MAX(\"time\") FROM weather.ecmwf WHERE $__timeFilter(\"time\"))\n  \nGROUP BY longitude, latitude, nuts_id\n--, 1\n--ORDER BY 1"
    }
   ]
  },
  {
   "title": "Weather Explorer $nuts_id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air\",\n  avg(ghi/3600) AS \"ghi\",\n  avg(\"wind_speed\") AS \"wind_speed\",\n  avg(SQRT(POWER(wind_meridional,2)+POWER(wind_zonal,2))) AS \"wind_speed_2\"\nFROM weather.ecmwf_eu\nWHERE\n  $__timeFilter(\"time\") AND\n  nuts_id like '$nuts_id%'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air_c\",\n  avg(ghi) AS \"ghi_c\",\n  avg(SQRT(POWER(wind_meridional,2)+POWER(wind_zonal,2))) AS \"wind_speed_c\"\nFROM weather.cosmo\nWHERE\n  $__timeFilter(\"time\") AND\n  nuts like '$nuts_id%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Weather Explorer",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air\",\n  avg(ghi/3600) AS \"ghi\",\n  avg(\"wind_speed\") AS \"wind_speed\"\nFROM weather.ecmwf_eu\nWHERE\n  $__timeFilter(\"time\") AND\n  nuts_id like 'DE%'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air_c\",\n  avg(ghi) AS \"ghi_c\",\n  avg(SQRT(POWER(wind_meridional,2)+POWER(wind_zonal,2))) AS \"wind_speed_c\"\nFROM weather.cosmo\nWHERE\n  $__timeFilter(\"time\") AND\n  country = 'DE'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Europe Windspeed map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  --$__timeGroupAlias(\"time\",$__interval),\n  --avg(temp_air-273.15) AS \"temp_air\",\n  --avg(ghi/3600) AS \"ghi\",\n  avg(\"wind_speed\") AS \"wind_speed\",\n  longitude,\n  latitude,\n  nuts_id\nFROM weather.ecmwf_eu\nWHERE\n  \"time\" = (SELECT MAX(\"time\") FROM weather.ecmwf WHERE $__timeFilter(\"time\"))\n  \nGROUP BY longitude, latitude, nuts_id\n--, 1\n--ORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Europe Irradiation map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  --$__timeGroupAlias(\"time\",$__interval),\n  --avg(temp_air-273.15) AS \"temp_air\",\n  avg(ghi/3600) AS \"ghi\",\n  --avg(\"wind_speed\") AS \"wind_speed\",\n  longitude,\n  latitude,\n  nuts_id\nFROM weather.ecmwf_eu\nWHERE\n  \"time\" = (SELECT MAX(\"time\") FROM weather.ecmwf WHERE $__timeFilter(\"time\"))\n  \nGROUP BY longitude, latitude, nuts_id\n--, 1\n--ORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Weather map",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  --$__timeGroupAlias(\"time\",$__interval),\n  avg(temp_air-273.15) AS \"temp_air\",\n  --avg(ghi/3600) AS \"ghi\",\n  --avg(\"wind_speed\") AS \"wind_speed\",\n  longitude,\n  latitude\nFROM weather.ecmwf\nWHERE\n  \"time\" = (SELECT MAX(\"time\") FROM weather.ecmwf WHERE $__timeFilter(\"time\"))\n  and\n  longitude > 5.5 and longitude < 7 AND\n  latitude > 50 and latitude < 51.3\n  \nGROUP BY longitude, latitude\n--, 1\n--ORDER BY 1"
    }
   ]
  }
 ]
}