FROM python:3.12-slim

COPY ./requirements.txt .

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN mkdir /src/grb_files

COPY ./crawler/nuts_mapper.py ./crawler/dwd.py ./crawler/base_crawler.py ./crawler/__init__.py /src/
COPY ./crawler/data/lat_coordinates.npy /src/data/
COPY ./crawler/data/lon_coordinates.npy /src/data/
COPY ./crawler/data/plz_matrix.npy /src/data/
COPY ./crawler/shapes /src/shapes

RUN chown -R admin /src

USER admin
WORKDIR /

CMD ["python", "-m", "src.dwd"]
