FROM python:3.12-slim

RUN pip install --no-cache-dir pandas requests sqlalchemy psycopg2-binary lxml
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir /src
RUN chown -R admin /src

COPY ./crawler/mastr.py ./crawler/common ./crawler/__init__.py /src/

USER admin
WORKDIR /src

CMD ["python", "-u","./mastr.py"]
