-- SPDX-FileCopyrightText: Florian Maurer, Christian Rieke
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

CREATE DATABASE axxteq;
CREATE DATABASE weather;
CREATE DATABASE eex;
CREATE DATABASE enet;
CREATE DATABASE entsoe;
CREATE DATABASE entsog;
CREATE DATABASE frequency;
CREATE DATABASE jao;
CREATE DATABASE mastr;
CREATE DATABASE nuts;
CREATE DATABASE ninja;
CREATE DATABASE scigrid;
CREATE DATABASE windmodel;
CREATE DATABASE opsd;
CREATE DATABASE e2watch;
CREATE DATABASE eview;